
### get all users
get http://localhost:3000/user/allMembers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxNzE1MGUzLTk5OWEtNGU2Yy1iM2U4LTEyZDM0MDZiMjZiNiIsImVtYWlsIjoibWlrZXZlbnVtOUBnbWFpbC5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzQ1MTc3MjYwLCJleHAiOjE3NDU3ODIwNjB9.nC8Z5a2wdfrnsgl3lCR10II83wRK4RBHsmRzcDePhhE



### add user
post http://localhost:3000/user/registerMember
Content-Type: application/json

{
    "first_name": "Test",
    "last_name": "Admin",
    "phone_number": "1234567890",
    "password": "Password123",
    "email": "userTests@gmail.com",
    "role": "admin"
    
}

### login user
post http://localhost:3000/user/loginMember
Content-Type: application/json

{
    "email": "mikevenum9@gmail.com",
    "password": "Password123"
}

